### ISSUE TITLE
Sample codes in README cannot be compiled

### ISSUE THREAD

**Issue by arowM** [robertjlooby/elm-generic-dict#5]
I found that sample codes in `README.md` produces compile errors.
There are two reasons why it fails to be compiled.
First, it uses `'` in variable name, which was unsupported after Elm 0.18.
Next, second argument of the `fromList` is not a list of Tuple.

P.S. I feel that this module has the best function design of all the similar libraries!

**Comment by robertjlooby** [comment]
Thanks for letting me know! I'll get it updated.

It's nice to know that people are still finding it useful 😄

**Comment by robertjlooby** [comment]
Fixed in https://github.com/robertjlooby/elm-generic-dict/pull/6

Thanks again!

**Comment by arowM** [comment]
Thanks!
